# ========================================
# 全局配置
# ========================================
logLevel = "debug"
# 是否启用数据源心跳检查（探活间隔受RetryIntervalSeconds参数控制 默认30s一次）
enableHealthPing = true
[[datasource]]
name = "prod_primary_01"
description = "生产环境主库-订单系统"
enabled = true
dbHost = "192.168.0.1:5236"
dbUser = "SYSDBA"
dbPwd = "Dameng123."  # 支持ENC()加密格式
labels = "env=prod,region=beijing,cluster=order_cluster"
[[datasource]]
name = "prod_primary_02"
description = "生产环境主库-订单系统B"
enabled = true
dbHost = "192.168.0.2:5236"
dbUser = "SYSDBA"
dbPwd = "Dameng123."  # 支持ENC()加密格式
labels = "env=prod,region=beijing,cluster=order_cluster"
bigKeyDataCacheTime=50
